/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MoreRouteImport } from './routes/more'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as ReaderWorkIdRouteImport } from './routes/reader.$workId'
import { Route as SeriesWorkIdRouteImport } from './routes/series.$workId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderWorkIdRoute = ReaderWorkIdRouteImport.update({
  id: '/reader/$workId',
  path: '/reader/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesWorkIdRoute = SeriesWorkIdRouteImport.update({
  id: '/series/$workId',
  path: '/series/$workId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/history': typeof HistoryRoute
  '/more': typeof MoreRoute
  '/settings': typeof SettingsRoute
  '/upcoming': typeof UpcomingRoute
  '/updates': typeof UpdatesRoute
  '/reader/$workId': typeof ReaderWorkIdRoute
  '/series/$workId': typeof SeriesWorkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/history': typeof HistoryRoute
  '/more': typeof MoreRoute
  '/settings': typeof SettingsRoute
  '/upcoming': typeof UpcomingRoute
  '/updates': typeof UpdatesRoute
  '/reader/$workId': typeof ReaderWorkIdRoute
  '/series/$workId': typeof SeriesWorkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/history': typeof HistoryRoute
  '/more': typeof MoreRoute
  '/settings': typeof SettingsRoute
  '/upcoming': typeof UpcomingRoute
  '/updates': typeof UpdatesRoute
  '/reader/$workId': typeof ReaderWorkIdRoute
  '/series/$workId': typeof SeriesWorkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/history'
    | '/more'
    | '/settings'
    | '/upcoming'
    | '/updates'
    | '/reader/$workId'
    | '/series/$workId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/history'
    | '/more'
    | '/settings'
    | '/upcoming'
    | '/updates'
    | '/reader/$workId'
    | '/series/$workId'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/history'
    | '/more'
    | '/settings'
    | '/upcoming'
    | '/updates'
    | '/reader/$workId'
    | '/series/$workId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  HistoryRoute: typeof HistoryRoute
  MoreRoute: typeof MoreRoute
  SettingsRoute: typeof SettingsRoute
  UpcomingRoute: typeof UpcomingRoute
  UpdatesRoute: typeof UpdatesRoute
  ReaderWorkIdRoute: typeof ReaderWorkIdRoute
  SeriesWorkIdRoute: typeof SeriesWorkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/$workId': {
      id: '/reader/$workId'
      path: '/reader/$workId'
      fullPath: '/reader/$workId'
      preLoaderRoute: typeof ReaderWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$workId': {
      id: '/series/$workId'
      path: '/series/$workId'
      fullPath: '/series/$workId'
      preLoaderRoute: typeof SeriesWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  HistoryRoute: HistoryRoute,
  MoreRoute: MoreRoute,
  SettingsRoute: SettingsRoute,
  UpcomingRoute: UpcomingRoute,
  UpdatesRoute: UpdatesRoute,
  ReaderWorkIdRoute: ReaderWorkIdRoute,
  SeriesWorkIdRoute: SeriesWorkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
